all: K-models.cpp peaks.cpp peaks.h stat.cpp stat.h DELibrary.cpp DELibrary.h RegressionLib.cpp RegressionLib.h
	g++ K-models.cpp peaks.cpp stat.cpp DELibrary.cpp RegressionLib.cpp -std=c++17 -lpthread -o K-models
	
